import React from 'react'
import Head from 'next/head'
import Link from "next/link";

const bachelor = () => {
 return (
    <div className='container mx-auto mb-8 px-10 md:px-0'>
      <Head>
        <title>Timon Keller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/TK_Logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      <div className='flex flex-col md:shadow-md md:shadow-black md:rounded-md mt-16 md:mt-24'>
        {<img src='/bachelor_cropped.png' className='rounded-md self-start'/>}
        <div className='md:px-20  mt-10 md:mt-20'>
          <h1 className='text-center md:text-start font-caveat text-orange dark:text-blue text-5xl md:text-6xl mb-10'>Real-time synchronization with an immersive, digital showroom</h1>
          <p className='text-center md:text-start text-text_light dark:text-text text-lg mb-24'>
            In the sixth semester of my studies at the FHNW I wrote my bachelor thesis. We were in a group of two students who worked together on the same project. 
            <br/>
            <br/>
            We had two customers in our project. The company pick-up-and-go, on the other hand, is a manufacturer of configurable bodies for pick-up trucks. The company Inside Reality focuses on an immersive, project-based solution that is able to present products, interactions and colla- borations as a group experience. The focus of this work is at the intersection of these two
            providers. Using an exemplary product of the company pick-up-and-go, the interactive presentation of this product in combination with a real-time interface to the immersive solution of Inside Reality will be investigated. Thus, a local exploration can be transformed into a space-based group experience - with possibilities of large-scale displays, real-time sharing and moderation.
            <br/>
            <br/>
            According to the initial situation, this project had two goals. On the one hand, a virtual, interactive showroom for a product is to be created in Unity. The focus is on emotional customer engagement as well as appealing visualization and interaction. These could be achieved e.g. at the interface of store, information, game and experience.
            On the other hand, it should be examined to what extent a real-time communication interface to the walk-through, room-based presentation solution of Inside Reality can be realized. In this context, the virtual showroom was to be presented independently, but synchronized in real-time with the local showroom in terms of representation and interaction.
          </p>
          <h1 className='text-center md:text-start text-orange dark:text-blue text-3xl mb-4'>
            My Role
          </h1>
          <p className='text-center md:text-start text-text_light dark:text-text text-lg mb-24'>
            Since there were only two of us in the project, we did not assign roles. So, for example, we worked with Agile but did not distribute Scrum roles.   
            I focused mainly on the showroom and the real-time solution via firebase and its data transfer.                
          </p>
          <h1 className='text-center md:text-start text-orange dark:text-blue text-3xl mb-4'>
            Project Difficulties
          </h1>
          <p className='text-center md:text-start text-text_light dark:text-text text-lg mb-12'>
            The difficulties in this project were that we had trouble transporting our client his CAD exports into Unity. We were able to work around this problem using blender and thus guarantee a good import quality of the CAD models. 
          </p>
          <a
          href="/bachelor_thesis.pdf"
          download
          target="_blank"
          className="self-center md:self-start "
        >
          <button className="font-caveat text-text_light dark:text-text border-text_light dark:border-text font-bold text-xl  border-2 rounded-md p-4 hover:bg-orange hover:border-orange hover:dark:bg-blue hover:dark:border-blue transform hover:-translate-y-2 hover:text-text transition-transform duration-200 ease-in mb-24">
            Download Thesis
          </button>
        </a>
        </div>
      </div>
    </div>
  )
}

export default bachelor


bachelor.getLayout = function getLayout(page) {
    return (
      <div>
        <Link href='javascript:history.back()'>
          <img src='/close_red.png' className='h-16 w-16 absolute top-8 md:top-16 right-[2%] md:right-0 lg:right-[6%] cursor-pointer'></img>
        </Link>
        {page}
      </div>
    )
}