import Head from 'next/head'
import { AboutMe, Contact, Projects, Services, TopPart } from '../components'

export default function Home() {
  return (
    <div className="container mx-auto mb-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
        <TopPart></TopPart>
        <AboutMe></AboutMe>
        <Services></Services>
        <Projects></Projects>
        <Contact></Contact>
    </div>
  )
}
